"""empty message

Revision ID: b76798b9767f
Revises: c032da7b1383
Create Date: 2023-09-15 13:58:37.282904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76798b9767f'
down_revision = 'c032da7b1383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'image')
    # ### end Alembic commands ###
