"""empty message

Revision ID: c032da7b1383
Revises: b5fa320442ba
Create Date: 2023-09-13 17:43:58.506514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c032da7b1383'
down_revision = 'b5fa320442ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'date')
    # ### end Alembic commands ###
